#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        useradd -m -p paxPtk/EBFGAg mcmyadmin
        chown mcmyadmin:mcmyadmin -R /home/mcmyadmin/McMyAdmin

        update-rc.d mcmyadmin defaults

        /etc/init.d/mcmyadmin
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0

