#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)

        if ! grep -q "^mcmyadmin:" /etc/passwd; then
            echo "Adding mcmyadmin user..."
            useradd -m -p paxPtk/EBFGAg mcmyadmin
        else
            echo "mcmyadmin user already exists."
        fi
        chown mcmyadmin:mcmyadmin -R /home/mcmyadmin/McMyAdmin

        update-rc.d mcmyadmin defaults

        /etc/init.d/mcmyadmin start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0

